### PR TITLE
Fix for Dict fields where values are primitive types

### PR DESCRIPTION
**Pull request by jcal-15**

### CODE REVIEW

**Comment by jcal-15** [comment]
Is this something you think is worth supporting?
I am pretty sure I know what changes are needed to support the following but it adds a bit of overhead. 

```python
class NormalClass:
    def __init__(self, n) -> None:
        self.n = f"Name: {n}"

@dataclass(frozen=True)
class KDict:
    a: int
    b: Optional[str]
    c: List[int]
    d: Dict[str, NormalClass]

opt = from_dict(KDict, a=11, b=None, c=[1, 2, 3], d={"a": NormalClass("m")})
```

**Comment by wchresta** [comment]
Oh yeah, I think we should support Dict[A, B] for A and B either structured types or primitives. If we dont't support that, yet, it's an oversight on my part.

Would be cool if you want to give it a go, but I also think it's an edge case. More likely, people will use structured types with named keys instead of Dicts.

**Comment by wchresta** [comment]
Great, thank you!

I'll wait with publishing version 0.3 until we get the cache change in, and then we can release everything as 0.3 together.

**Comment by wchresta** [comment]
Oh yeah, I think we should support Dict[A, B] for A and B either structured
types or primitives. If we dont't support that, yet, it's an oversight on
my part.

Would be cool if you want to give it a go, but I also think it's an edge
case. More likely, people will use structured types with named keys instead
of Dicts.

**Pull request merged**
