### PR TITLE
Adding data-classes for passing state around.

### PR DESCRIPTION
**Pull request by jcal-15**
@wchresta, Sorry for all the pull requests lately. This is not really a PR. I just wanted to get your opinion about a change to the the code I was thinking about. 

I was working on updates to PR #4 and stated thinking that it might be better to use data-classes to pass the parameters around.

### CODE REVIEW

**Comment by jcal-15** [comment]
Oh, I forgot data-classes were not in Python 3.6. 
What are your thoughts for adding [dataclasses](https://pypi.org/project/dataclasses/) as a dependency for Python 3.6?

**Comment by jcal-15** [comment]
If you like this change, I am thinking now that it would be best to merge it into main. This way the other changes become easier to see.

**Comment by wchresta** [comment]
Python 3.6 is end-of-life. We don't need to support it anymore. I'll drop the test for it and then this should pass.

**Comment by wchresta** [comment]
Apart from the 3.6 thing, there's a difficult balance that should be found here.
In one extreme case, every little argument is passed around on its own, which can be cumbersome (current state of the code).
In the other extreme case, all arguments that any function could possibly want is bulked into a single state type and passed around. In this extreme case, it's very convenient because everything you'll ever need is in the state and everything has it, but it becomes very hard to untangle it. If something is in the state, it's suddenly not obvious anymore which part of the code needs or modifies it, and it basically becomes a global variable. We don't want this second extreme to happen.
So I would be careful throwing everything into a dataclass and passing it around. Things that strongly belong together can be passed around together (for example global_ns and local_ns just kind of belong together and you'd never really need one without the other). So if we want to go this direction, I'd want us to be careful to only group things together in a dataclass that really belong together and not more.

**Comment by jcal-15** [comment]
You make good points about putting too much into the data-classes. I will see if I can clean up the data-class a bit. 
If you don't think it is worth the change I am fine with it too.

To give you an idea of why I started looking into this, here is a an early version of the changes I am working on. I have split out the list handling code into anther function and created a function for handling union. 
https://github.com/jcal-15/from-dict/commit/c49768607631b0c7d4aa173ac93f1c9812ae5ebc

I guess the main thing I want to get away from it passing all these partial functions around. Their type-hints are too long to be helpful and I think it would be a lot nicer to right click on them and be able to go to definition.

**Comment by jcal-15** [comment]
Killing this PR for now. I think that an `ArgumentState` class is still something worth exploring but for now this code is too out of sync with my other changes to keep this open.

**Pull request closed without merging**
